version: "3"
services:
  algo_app:
    container_name: myc
    build: .
    volumes:
      - ./ml_mount:/opt/ml_mount
    ports:
      - 8080:8080
    command: tail -f /dev/null # keep the container running
